"""Application constants."""

from __future__ import annotations

DECK_SIZE = 78
CARD_ID_MIN = 0
CARD_ID_MAX = 77

MAX_SLOT_TEXT_CHARS = 2500
MAX_TELEGRAM_MESSAGE = 4096
MAX_TELEGRAM_CAPTION = 1024
MIN_INTERPRETATION_CHARS = 80
MIN_SECTION_BODY_CHARS = 100
LABEL_ONLY_BODY_CHARS = 40

LLM_CONNECT_TIMEOUT = 30
LLM_TOTAL_TIMEOUT = 120
LLM_MAX_RETRIES = 3
LLM_MAX_CONCURRENCY = 5

TELEGRAM_MAX_RETRIES = 3
TELEGRAM_POLL_TIMEOUT = 30
TELEGRAM_HTTP_READ_TIMEOUT = 60
TELEGRAM_HTTP_CONNECT_TIMEOUT = 10
TELEGRAM_HTTP_WRITE_TIMEOUT = 15
TELEGRAM_HTTP_POOL_TIMEOUT = 10
DAILY_BATCH_SIZE = 20

SPREAD_SINGLE = "single"
SPREAD_THREE = "three"
SPREAD_DAILY = "daily"

SPREAD_REQUIRED_SECTIONS: dict[str, tuple[str, ...]] = {
    SPREAD_THREE: ("Прошлое", "Настоящее", "Будущее"),
}

MAX_INTERPRETATION_CHARS: dict[str, int] = {
    SPREAD_SINGLE: 800,
    SPREAD_THREE: 1600,
    SPREAD_DAILY: 550,
}

PROCESSING_MESSAGES: dict[str, str] = {
    SPREAD_SINGLE: "🔮 Толкую карту…",
    SPREAD_THREE: "🔮 Толкую расклад…",
    SPREAD_DAILY: "🔮 Карта дня…",
}

FOCUS_PROMPT_MESSAGE = "Задайте свой вопрос или подумайте о нём…"
FOCUS_PAUSE_SECONDS = 2.5
INTERPRETING_MIN_VISIBLE_SECONDS = 0.5

READING_STATUS_PENDING = "pending"
READING_STATUS_COMPLETED = "completed"
READING_STATUS_FAILED = "failed"

DELIVERY_NONE = "none"
DELIVERY_PENDING = "pending"
DELIVERY_SENT = "sent"
DELIVERY_FAILED = "failed"
