"""Application constants."""

from __future__ import annotations

DECK_SIZE = 78
CARD_ID_MIN = 0
CARD_ID_MAX = 77

MAX_SLOT_TEXT_CHARS = 2500
MAX_TELEGRAM_MESSAGE = 4096
MAX_TELEGRAM_CAPTION = 1024
MIN_INTERPRETATION_CHARS = 80

LLM_CONNECT_TIMEOUT = 30
LLM_TOTAL_TIMEOUT = 120
LLM_MAX_RETRIES = 3
LLM_MAX_CONCURRENCY = 5

TELEGRAM_MAX_RETRIES = 3
DAILY_BATCH_SIZE = 20

SPREAD_SINGLE = "single"
SPREAD_THREE = "three"
SPREAD_DAILY = "daily"

MAX_INTERPRETATION_CHARS: dict[str, int] = {
    SPREAD_SINGLE: 650,
    SPREAD_THREE: 950,
    SPREAD_DAILY: 450,
}

PROCESSING_MESSAGES: dict[str, str] = {
    SPREAD_SINGLE: "🔮 Толкую карту…",
    SPREAD_THREE: "🔮 Толкую расклад…",
    SPREAD_DAILY: "🔮 Карта дня…",
}

READING_STATUS_PENDING = "pending"
READING_STATUS_COMPLETED = "completed"
READING_STATUS_FAILED = "failed"

DELIVERY_NONE = "none"
DELIVERY_PENDING = "pending"
DELIVERY_SENT = "sent"
DELIVERY_FAILED = "failed"
